---
name: Release
on:  # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  # Builds the Dockerfile and pushes it to dockerhub and GHCR
  release:
    name: Release - Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker - GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
          flavor: latest=true

      - name: Docker - Metadata (Root)
        id: meta_root
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=root
            type=semver,pattern=root-v{{version}}
            type=semver,pattern=root-v{{major}}.{{minor}}
            type=semver,pattern=root-v{{major}}
          flavor: latest=false

      - name: Docker - Metadata (Proton)
        id: meta_proton
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=proton
            type=semver,pattern=proton-v{{version}}
            type=semver,pattern=proton-v{{major}}.{{minor}}
            type=semver,pattern=proton-v{{major}}
          flavor: latest=false

      - name: Docker - Build / Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          target: container
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            GIT_VERSION_TAG=${{ github.event.release.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker - Build / Push (Root)
        id: docker_build_root
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          target: container-root
          push: true
          tags: ${{ steps.meta_root.outputs.tags }}
          build-args: |
            GIT_VERSION_TAG=${{ github.event.release.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker - Build / Push (Proton)
        id: docker_build_proton
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          target: container-proton
          push: true
          tags: ${{ steps.meta_proton.outputs.tags }}
          build-args: |
            GIT_VERSION_TAG=${{ github.event.release.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
